### ISSUE TITLE
端口冲突

### ISSUE THREAD

**Issue by shinepreventer** [Alen-QK/python-crawler#11]
与kavita端口冲突，使用docker compose部署时无法连接kavita

 获取Kavita授权失败： HTTPConnectionPool(host='172.17.0.4', port=5000): Max retries exceeded with url: //api/Plugin/authenticate?apiKey=***********&pluginName=pythonScanScript (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff77d16e7f0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

version: "3"
services:
    vanislord_manga:
        container_name: vanislord
        environment:
            - PYTHONUNBUFFERED=1
            - MANGA_BASE_URL=http://localhost:5001
            - MANGA_BASE_WEBSOCKET_URL=http://localhost:5001
            - KAVITA_BASE_URL=http://172.17.0.4:5000/
            - KAVITA_EXPOSE_URL=http://172.17.0.4:5000/
            - KAVITA_ADMIN_APIKEY=************
            - KAVITA_LIB_ID=1
            - FLARESOLVERR_URL=http://172.27.0.2:8191
            - NUMBER_OF_WORKERS=2
        volumes:
            - type: bind
              source: /Download/comics
              target: /downloaded
            - type: bind
              source: /Download/comics/config
              target: /vanmanga/eng_config
            - type: bind
              source: /Download/comics/thumbnails
              target: /vanmanga/thumbnails
        ports:
            - 5001:5000
        image: wzl778633/vanislord_manga:latest

    flaresolverr:
        container_name: flaresolverr
        ports:
            - 8191:8191
        environment:
            - LOG_LEVEL=info
        restart: unless-stopped
        image: ghcr.io/flaresolverr/flaresolverr:latest

    kavita:
       image: jvmilazz0/kavita:latest   
       container_name: kavita
       restart: unless-stopped
       network_mode: bridge
       environment:
         TZ: Asia/Shanghai
       ports:
         - 5000:5000
       volumes:
         - ./manga:/config:/manga
         - /Download/comics:/comics
         - /Download/books:/books 
         - ./config:/kavita/config

**Comment by Alen-QK** [comment]
部署方式有几处需要修改的地方：

1. **KAVITA_BASE_URL & KAVITA_EXPOSE_URL** 请不要在最后追加`/`，系统默认会携带该字符，此处会导致地址拼接错误
2. 请确认**KAVITA_ADMIN_APIKEY**是否已经生成，并正确填入。因为你正在使用docker-compose进行批处理，所以如果你同时初始化vanmanga和Kavita，而Kavita还未注册任何管理员账户，那么你是未拥有APIKEY的状态。docker-compose处理的正确顺序是，初始化均启动后，删除vanmanga容器；完成Kavita注册，获取管理员APIKEY，并初始化库；将APIKEY填入docker-compose.yml文件，单独初始化vanmanga。
3. 如果是使用内部桥接的形式，更加推荐直接使用容器名来请求Kavita的服务，避免docker可能对172的内部地址自动变动等

此外，目前源网站并没有激活cloudflare服务，所以暂时可以不需要开启bypasser，对应容器可以删去。

以下docker-compose请供参考：

```
version: "3"

services:
  vanislord_manga:
    container_name: vanislord
    image: wzl778633/vanislord_manga:latest
    environment:
      - PYTHONUNBUFFERED=1
      - MANGA_BASE_URL=http://localhost:5001
      - MANGA_BASE_WEBSOCKET_URL=http://localhost:5001
      - KAVITA_BASE_URL=http://kavita:5000            # 用容器名kavita代替IP
      - KAVITA_EXPOSE_URL=http://kavita:5000           # 同上
      - KAVITA_ADMIN_APIKEY=d4ec975c-XXXX-XXXX-XXXX-XXXX33e1               # 你自己的API Key
      - KAVITA_LIB_ID=1
      - NUMBER_OF_WORKERS=2
    volumes:
      - /Download/comics:/downloaded
      - /Download/comics/config:/vanmanga/eng_config
      - /Download/comics/thumbnails:/vanmanga/thumbnails
    ports:
      - "5001:5000" 
    networks:
      - van_network

  kavita:
    container_name: kavita
    image: jvmilazz0/kavita:latest
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "5000:5000"
    volumes:
      - ./manga:/config/manga
      - /Download/comics:/comics
      - /Download/books:/books
      - ./config:/kavita/config
    networks:
      - van_network

networks:
  van_network:
    driver: bridge
```
